length = float(input("Enter the length of the cuboid "))
breadth = float(input("Enter the breadth of the cuboid "))
height = float(input("Enter the height of the cuboid "))
TSA = 2*(length*breadth+breadth*height+height*length)
print ("The total surface area of the cuboid is ",TSA)